# Generated by Django 4.2.4 on 2023-10-20 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permisos', '__first__'),
        ('userprofile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='NULL', upload_to='img', verbose_name='Imagen')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('eliminada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(to='permisos.rolesdesistema')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=500, verbose_name='Titulo')),
                ('image', models.ImageField(default='NULL', upload_to='img', verbose_name='Logo')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('En Creacion', 'En Creacion'), ('En Edicion', 'En Edicion'), ('En publicacion', 'En Publicacion'), ('Desactivado', 'Desactivado')], default='En Creacion', max_length=20)),
                ('tipo', models.CharField(choices=[('Texto', 'Texto'), ('Imagenes', 'Imagenes'), ('Combinados', 'Combinados'), ('Otros', 'Otros')], default='Texto', max_length=20)),
                ('carrousel', models.ManyToManyField(blank=True, to='cmsapp.carrousel', verbose_name='Imagenes')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.category', verbose_name='Categoria')),
                ('dislikes', models.ManyToManyField(related_name='blog_post2', to='userprofile.userprofile')),
                ('likes', models.ManyToManyField(related_name='blog_post', to='userprofile.userprofile')),
                ('miembros', models.ManyToManyField(related_name='set_miembros', to=settings.AUTH_USER_MODEL, verbose_name='Miembros')),
                ('roles', models.ManyToManyField(to='permisos.rolesdesistema')),
                ('usuario_roles', models.ManyToManyField(to='cmsapp.rolusuario')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.userprofile', verbose_name='Creador')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Escriba un comentario...', max_length=2000, verbose_name='Comentario')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.post')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
