# Generated by Django 4.2.4 on 2023-08-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tittle',
            new_name='title',
        ),
    ]
