# Generated by Django 4.2.4 on 2023-08-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_post_writter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writter',
            new_name='writer',
        ),
    ]
