# Generated by Django 4.2.4 on 2023-11-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.TextField(default='Más detalles...', help_text='Escriba detalladamente', max_length=200),
        ),
    ]
