# Generated by Django 4.2.4 on 2023-12-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0010_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
