# Generated by Django 4.2.4 on 2023-12-14 18:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0011_remove_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='carrousel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
