# Generated by Django 4.2.4 on 2023-10-19 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permisos', '0011_delete_rolusuario'),
        ('cmsapp', '0014_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='miembros',
            field=models.ManyToManyField(related_name='set_miembros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='roles',
            field=models.ManyToManyField(to='permisos.rolesdesistema'),
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(to='permisos.rolesdesistema')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='usuario_roles',
            field=models.ManyToManyField(to='cmsapp.rolusuario'),
        ),
    ]
