# Generated by Django 4.2.4 on 2023-10-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0016_alter_post_miembros_alter_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('En Creacion', 'En Creacion'), ('En Edicion', 'En Edicion'), ('En publicacion', 'En publicacion'), ('Desactivado', 'Desactivado')], default='En Creacion', max_length=20),
        ),
    ]
