# Generated by Django 4.2.4 on 2023-10-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0017_post_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('Texto', 'Texto'), ('Imagenes', 'Imagenes'), ('Combinados', 'Combinados'), ('Otros', 'Otros')], default='Texto', max_length=20),
        ),
    ]
