# Generated by Django 4.2.4 on 2023-10-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0016_tarea_eliminada'),
        ('cmsapp', '0018_post_tipo'),
    ]

    operations = [
    ]
