# Generated by Django 4.2.4 on 2023-10-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0019_merge_0016_tarea_eliminada_0018_post_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='NULL', upload_to='img', verbose_name='Imagen')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('En Creacion', 'En Creacion'), ('En Edicion', 'En Edicion'), ('En publicacion', 'En Publicacion'), ('Desactivado', 'Desactivado')], default='En Creacion', max_length=20),
        ),
    ]
