# Generated by Django 4.2.4 on 2023-10-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0020_carrousel_alter_post_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carrousel',
            field=models.ManyToManyField(blank=True, null=True, to='cmsapp.carrousel', verbose_name='Imagenes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
