from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<str:categoria>', views.indexCat, name='indexCat'),
    path('reportes-pdf/', views.reportes_pdf, name='reportes_pdf'),
    # path('test/<str:categoria>', views.pregunta, name='test'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('dislike-post/<str:slug>', views.dislikePost, name= 'dislike'),
    path('article/<str:slug>', views.detail, name= 'detail'),
    path('create-post', views.createPost, name= 'create'),
    path('update-post/<str:slug>', views.updatePost, name= 'update'),
    path('delete-post/<str:slug>', views.deletePost, name= 'delete'),
    path('publish-post/<str:slug>', views.publishPost, name='publish'),
    path('like-post/<str:slug>', views.likePost, name= 'like'),
    path('dislike-post/<str:slug>', views.dislikePost, name= 'dislike'),
    path('list-category', views.listCategory.as_view(), name= 'listCategory'),
    path('post/<slug:slug>', views.PostView.as_view(), name= 'post'),
    path('count_comments/<int:post_id>/', views.count_comments, name='count_comments'),
    path('create-category', views.createCategory, name= 'createCategory'),
    path('update-category/<str:slug>', views.updateCategory, name= 'updateCategory'),
    path('delete-category/<str:slug>', views.deleteCategory, name= 'deleteCategory'),
    path('eliminar-comentario/', views.delete_comment, name= 'delete_comment'),
    path('asignar_miembro/<str:slug>', views.asignarMiembro, name='asignar_miembro'),
    path('asignar_rol/<str:slug>/miembro/<int:id_usuario>', views.asignarRol, name='asignar_rol'),
    path('generar-pdf/', views.pdf_view, name='generar_pdf'),
    path('reportes-pdf/grafico-visualizaciones/', views.grafico_visualizaciones, name='grafico_visualizaciones'),
    path('reportes-pdf/grafico-estados/', views.grafico_estados, name='grafico_estados'),
    path('reportes-pdf/grafico-denuncias/', views.grafico_denuncias, name='grafico_denuncias'),

    path('kanban-board/', views.kanban_board, name='kanban-board'),
    # path('crear-tarea/', views.crear_tarea, name='crear-tarea'),  # Nueva URL para el formulario de creación
    path('mover-post/<str:slug>/<str:nuevo_estado>/', views.mover_post, name='mover-post'),
    path('desactivar/', views.desactivar_post, name='desactivar-post'),
    path('reportar/<str:slug>/', views.report_post, name='reportar_publicacion'),
    path('estadisticas_post/<str:slug>/', views.estadisticas_post, name='estadisticas_post'),
    path('reportes-pdf/reporte_categoria/', views.reporte_categoria, name='reporte_categoria'),
]