# Generated by Django 4.2.4 on 2023-10-20 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('username', models.CharField(max_length=200, verbose_name='Nombre de Usuario')),
                ('profession', models.CharField(max_length=200, verbose_name='Profesion')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Foto')),
                ('about', models.TextField(verbose_name='Sobre mi')),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
