# Generated by Django 4.2.4 on 2023-11-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_notificaciones_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
        ),
    ]
