# Generated by Django 4.2.4 on 2023-09-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_alter_rolesdesistema_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolesdesistema',
            options={'permissions': [('_acceder_al_sistema', 'Acceder al sistema'), ('_crear_usuario', 'Crear usuario')]},
        ),
    ]
