# Generated by Django 4.2.4 on 2023-09-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0004_alter_rolesdesistema_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolesdesistema',
            options={'permissions': [('acceder_al_sistema', 'Acceder al Sistema'), ('administrar_rol', 'Administrar Rol'), ('crear_rol', 'Crear Rol'), ('modificar_rol', 'Modificar Rol'), ('eliminar_rol', 'Eliminar Rol'), ('editar_perfil', 'Editar Perfil'), ('administrar_categoria', 'Administrar Categoria'), ('crear_categoria', 'Crear Categoria'), ('editar_categoria', 'Editar Categoria'), ('eliminar_categoria', 'Eliminar Categoria'), ('configurar_sitio_web', 'Configurar Sitio Web'), ('administrar_contenido', 'Administrar Contenido'), ('crear_contenido', 'Crear Contenido'), ('editar_contenido', 'Editar Contenido'), ('eliminar_contenido', 'Eliminar Contenido'), ('publicar_contenido', 'Publicar Contenido'), ('asignar_categoria_a_contenido', 'Asignar Categoria a Contenido'), ('ver_estadistica_de_contenido', 'Ver estadistica del contenido'), ('ver_numero_de_visualizaciones', 'Ver Numero de visualizaciones'), ('ver_numero_de_likes', 'Ver numero de likes'), ('ver_numero_de_dislikes', 'Ver numero de dislikes'), ('comentar_contenido', 'Comentar contenido'), ('administrar_tipo_de_contenido', 'Administar tipo de contenido'), ('crear_tipo_de_contenido', 'Crear tipo de contenido'), ('editar_tipo_de_contenido', 'editar tipo de contenido'), ('eliminar_tipo_de_contenido', 'Eliminar tipo de contenido'), ('filtrar_contenidos_por_categoria', 'Filtrar contenidos por categoria'), ('filtrar_contenidos_por_tipo', 'Filtrar contenidos por tipo'), ('notificar_eventos', 'Notificar eventos'), ('notificar_solicitud_de_edicion', 'Notificar solicitud de edicion'), ('notificar_solicitud_de_publicacion', 'Notificar solicitud de publicacion'), ('notificar_publicacion_del_contenido', 'Notificar solicitud de contenido'), ('administrar_estado', 'Administrar estado'), ('crear_estado', 'Crear Estado'), ('modificar_estado', 'Modificar estado'), ('eliminar_estado', 'Eliminar estado'), ('visualizar_tablero_kanban', 'Visualizar tablero Kanban'), ('modificar_tablero_kanban', 'Modificar tablero Kanban'), ('visualizar_historial', 'Visualizar historial'), ('visualizar_reporte', 'Visualizar reporte')]},
        ),
    ]
