# Generated by Django 4.2.4 on 2023-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_delete_rolusuario'),
        ('permisos', '0006_alter_rolesdesistema_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesdesistema',
            name='rol_usuario',
            field=models.ManyToManyField(blank=True, to='userprofile.userprofile'),
        ),
    ]
