# Generated by Django 4.2.4 on 2023-10-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0007_rolesdesistema_rol_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolesdesistema',
            name='rol_usuario',
        ),
    ]
