# Generated by Django 4.2.4 on 2023-10-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_delete_rolusuario'),
        ('permisos', '0008_remove_rolesdesistema_rol_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
                ('roles', models.ManyToManyField(to='permisos.rolesdesistema')),
            ],
        ),
    ]
