# Generated by Django 4.2.4 on 2023-10-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0010_alter_rolusuario_miembro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolUsuario',
        ),
    ]
