# Generated by Django 4.2.4 on 2023-10-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0011_delete_rolusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesdesistema',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Rol de Sistema'),
        ),
    ]
